language: python
sudo: required
python:
- '3.6'
install:
- pip install -r requirements.txt
script:

- cd application/auth && coverage run test_login.py
- cd ~
- cd application/auth && coverage run test_registration.py
- cd ~
- cd application/book && coverage run tests.py
after_success:
- coveralls
dist: xenial
